
services:
  postgres1:
    build:
      context: . 
    image: my-image
    environment:
      POSTGRES_PASSWORD: my_password
    container_name: my-postgres-dc-container1
    ports:
      - "5432:5432"  # Map container's port 5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data 

volumes:
  postgres_data:

