name: Build and Slim Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch

jobs:
  build-and-slim:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/my-image:latest .

    # Step 4: Install Docker Slim
    - name: Install Docker Slim
      run: |
        curl -L -o docker-slim.tar.gz https://github.com/slimtoolkit/slim/releases/download/1.40.11/dist_linux.tar.gz
        tar -xzf docker-slim.tar.gz
        chmod +x dist_linux/docker-slim
        sudo mv dist_linux/docker-slim /usr/local/bin/

    # Step 5: Slim the Docker image
    - name: Slim Docker image
      run: |
        docker-slim build \
          --http-probe=false \
          --continue-after=nothing \
          ghcr.io/${{ github.repository_owner }}/my-image:latest

    # Step 6: Tag the slimmed image
    - name: Tag slimmed image
      run: |
        docker tag ghcr.io/${{ github.repository_owner }}/my-image.slim ghcr.io/${{ github.repository_owner }}/my-image:slim

    # Step 7: Push the slimmed image to GitHub Container Registry
    - name: Push slim Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my-image:slim
